/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-1-ga49a51a

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: DS301_profile.xpd
        File Version: 1

        Created:      23. 11. 2020 12:00:00
        Created By:   
        Modified:     17. 03. 2023 02:07:28
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: New Product
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
//added by me
#define OD_CNT_ARR_1029 1
#define OD_CNT_ARR_1F50 1
#define OD_CNT_ARR_1F51 1
#define OD_CNT_ARR_1F56 1
#define OD_CNT_ARR_1F57 1
#define OD_CNT_ARR_210C 4
#define OD_CNT_ARR_30A4 1
#define OD_CNT_ARR_30D1 2
#define OD_CNT_ARR_30D2 1
#define OD_CNT_ARR_30D3 1
#define OD_CNT_ARR_3141 2
#define OD_CNT_ARR_3142 4
#define OD_CNT_ARR_3150 2
#define OD_CNT_ARR_3151 2
#define OD_CNT_ARR_3160 2
#define OD_CNT_ARR_3161 2
#define OD_CNT_ARR_3162 2
#define OD_CNT_ARR_3170 4
#define OD_CNT_ARR_3171 4
#define OD_CNT_ARR_31E0 4
#define OD_CNT_ARR_31E1 2
#define OD_CNT_ARR_31E4 2
#define OD_CNT_ARR_31E6 2
#define OD_CNT_ARR_31E7 2
#define OD_CNT_ARR_31E8 2
#define OD_CNT_ARR_31E9 2
#define OD_CNT_ARR_3248 2
#define OD_CNT_ARR_607B 2
#define OD_CNT_ARR_607D 2
#define OD_CNT_ARR_6099 2
#define OD_CNT_ARR_60D0 1
#define OD_CNT_ARR_60E3 15
#define OD_CNT_ARR_60FE 1
//end added by me

/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint8_t x1003_errorHistory_sub0;//
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    uint8_t x1029_errorBehavior_sub0;//
        uint8_t x1029_errorBehavior[OD_CNT_ARR_1029];//
        struct {
                uint8_t highestSub_indexSupported;
                uint32_t COB_ID_SDOClientToServer;
                uint32_t COB_ID_SDOServerToClient;
            } x1200_SDOServerParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;//
                uint32_t applicationObject10;//
                uint32_t applicationObject11;//
                uint32_t applicationObject12;//
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
        uint32_t applicationObject9;
        uint32_t applicationObject10;
        uint32_t applicationObject11;
        uint32_t applicationObject12;
    } x1A03_TPDOMappingParameter;
    //
    uint8_t x1F50_programData_sub0;
        uint8_t x1F51_programControl_sub0;
        uint8_t x1F51_programControl[OD_CNT_ARR_1F51];
        uint8_t x1F56_programSoftwareIdentification_sub0;
        uint8_t x1F57_flashStatusIdentification_sub0;
        uint8_t x2000_node_ID;
        uint8_t x2001_CANBitRate;
        uint16_t x2006_USBFrameTimeout;
        struct {
            uint8_t highestSub_indexSupported;
        } x2100_additionalIdentity;
        uint8_t x210C_customPersistentMemory_sub0;
        uint32_t x210C_customPersistentMemory[OD_CNT_ARR_210C];
        struct {
            uint8_t highestSub_indexSupported;
        } x2200_powerSupply;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t powerSupplyUndervoltageLimit;
            uint32_t powerSupplyOvervoltageLimit;
        } x2201_powerSupplySupervision;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t internalErrorControl;
            uint8_t internalLED_Identification;
        } x2EC0_internalDeviceControl;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t controlStructure;
            uint32_t axisConfigurationMiscellaneous;
        } x3000_axisConfiguration;
        struct {
            uint8_t highestSub_indexSupported;
        } x3001_motorData;
        struct {
            uint8_t highestSub_indexSupported;
        } x3002_electricalSystemParameters;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t gearReductionNumerator;
            uint32_t gearReductionDenominator;
            uint32_t maxGearInputSpeed;
            uint32_t gearMiscellaneousConfiguration;
        } x3003_gearConfiguration;
        struct {
            uint8_t highestSub_indexSupported;
        } x3012_SSIAbsoluteEncoder;
        struct {
            uint8_t highestSub_indexSupported;
        } x30A0_currentControlParameterSet;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t positionControllerPGain;
            uint32_t positionControllerIGain;
            uint32_t positionControllerDGain;
            uint32_t positionControllerFFVelocityGain;
            uint32_t positionControllerFFAccelerationGain;
            uint32_t SIUnitPositionControllerIGain;
        } x30A1_positionControlParameterSet;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t velocityControllerPGain;
            uint32_t velocityControllerIGain;
            uint32_t velocityControllerFFVelocityGain;
            uint32_t velocityControllerFFAccelerationGain;
            uint16_t velocityControllerFilterCut_offFrequency;
        } x30A2_velocityControlParameterSet;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t velocityObserverPositionCorrectionGain;
            uint32_t velocityObserverVelocityCorrectionGain;
            uint32_t velocityObserverLoadCorrectionGain;
            uint32_t velocityObserverFriction;
            uint32_t velocityObserverInertia;
        } x30A3_velocityObserverParameterSet;
        uint8_t x30A4_internalVelocityFilterParameterSet_sub0;
        uint32_t x30A4_internalVelocityFilterParameterSet[OD_CNT_ARR_30A4];
        int32_t x30B0_homePosition;
        int32_t x30B1_homeOffsetMoveDistance;
        uint16_t x30B2_currentThresholdForHomingMode;
        struct {
            uint8_t highestSub_indexSupported;
            int32_t internalAbsoluteHomeReference;
            uint8_t internalAbsoluteHomeReferenceState;
        } x30B5_internalHomingData;
        uint8_t x30D1_currentActualValues_sub0;
        uint8_t x30D2_torqueActualValues_sub0;
        uint8_t x30D3_velocityActualValues_sub0;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t standstillWindow;
            uint16_t standstillWindowTime;
            uint16_t standstillWindowTimeout;
        } x30E0_standstillWindowConfiguration;
        uint8_t x3141_digitalInputProperties_sub0;
        uint16_t x3141_digitalInputProperties[OD_CNT_ARR_3141];
        uint8_t x3142_configurationOfDigitalInputs_sub0;
        uint8_t x3142_configurationOfDigitalInputs[OD_CNT_ARR_3142];
        uint8_t x3150_digitalOutputProperties_sub0;
        uint16_t x3150_digitalOutputProperties[OD_CNT_ARR_3150];
        uint8_t x3151_configurationOfDigitalOutputs_sub0;
        uint8_t x3151_configurationOfDigitalOutputs[OD_CNT_ARR_3151];
        struct {
            uint8_t highestSub_indexSupported;
            uint16_t holdingBrakeRiseTime;
            uint16_t holdingBrakeFallTime;
        } x3158_holdingBrakeParameters;
        uint8_t x3160_analogInputProperties_sub0;
        uint8_t x3161_configurationOfAnalogInputs_sub0;
        uint8_t x3161_configurationOfAnalogInputs[OD_CNT_ARR_3161];
        uint8_t x3162_analogInputGeneralPurpose_sub0;
        struct {
            uint8_t highestSub_indexSupported;
            int16_t analogInput1AdjustmentOffset;
            uint16_t analogInput1AdjustmentGainFactor;
            int16_t analogInput2AdjustmentOffset;
            uint16_t analogInput2AdjustmentGainFactor;
        } x3163_analogInputAdjustment;
        uint8_t x3170_analogInputCurrentSetValueProperties_sub0;
        int32_t x3170_analogInputCurrentSetValueProperties[OD_CNT_ARR_3170];
        uint8_t x3171_analogInputVelocitySetValueProperties_sub0;
        int32_t x3171_analogInputVelocitySetValueProperties[OD_CNT_ARR_3171];
        uint8_t x31E0_internalDataRecorderVariableIndex_sub0;
        uint32_t x31E0_internalDataRecorderVariableIndex[OD_CNT_ARR_31E0];
        uint8_t x31E1_internalDataRecorderConfiguration_sub0;
        uint16_t x31E1_internalDataRecorderConfiguration[OD_CNT_ARR_31E1];
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t internalDataRecorderTriggerVariableIndex;
            uint8_t internalDataRecorderTriggerMode;
            uint32_t internalDataRecorderTriggerHighValue;
            uint32_t internalDataRecorderTriggerLowValue;
            uint32_t internalDataRecorderTriggerMask;
            uint16_t internalDataRecorderTriggerNumberOfPrecedingSamples;
        } x31E2_internalDataRecorderTrigger;
        uint8_t x31E4_internalDataRecorderControl_sub0;
        uint16_t x31E4_internalDataRecorderControl[OD_CNT_ARR_31E4];
        struct {
            uint8_t highestSub_indexSupported;
        } x31E5_internalDataRecorderData;
        uint8_t x31E6_internalDataRecorderBufferVariable1_sub0;
        uint8_t x31E7_internalDataRecorderBufferVariable2_sub0;
        uint8_t x31E8_internalDataRecorderBufferVariable3_sub0;
        uint8_t x31E9_internalDataRecorderBufferVariable4_sub0;
        struct {
            uint8_t highestSub_indexSupported;
        } x3200_powerLimitation;
        struct {
            uint8_t highestSub_indexSupported;
            uint16_t maximalTemperaturePowerStage;
        } x3201_thermalOverloadProtection;
        struct {
            uint8_t highestSub_indexSupported;
        } x3203_motorControl;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t internalSpiExtensionTest;
        } x3240_internalTestObject;
        struct {
            uint8_t highestSub_indexSupported;
            int16_t internalADCCurrentOffsetSimultaneousPhaseU;
            int16_t internalADCCurrentOffsetSimultaneousPhaseV;
            int16_t internalADCCurrentOffsetSequentialPhaseU;
            int16_t internalADCCurrentOffsetSequentialPhaseV;
            int16_t internalADCCurrentOffsetSequentialPhaseW;
        } x3241_internalMotorControl;
        uint8_t x3248_internalConfigurationElectricalSystemTuning_sub0;
        uint16_t x3248_internalConfigurationElectricalSystemTuning[OD_CNT_ARR_3248];
        struct {
            uint8_t highestSub_indexSupported;
        } x3249_internalParametersElectricalSystemTuning;
        struct {
            uint8_t highestSub_indexSupported;
            uint32_t internalCut_offFrequencyOfOscillation;
            uint32_t internalTargetAmplitudeOfOscillation;
            uint32_t internalProportionalGainForDynamicFriction;
            uint32_t internalIntegralGainForDynamicFriction;
        } x324B_internalConfigurationMechanicalSystemTuning;
        struct {
            uint8_t highestSub_indexSupported;
        } x324C_internalParametersMechanicalSystemTuning;
        int16_t x6007_abortConnectionOptionCode;
        uint16_t x6040_controlword;
        int16_t x605A_quickStopOptionCode;
        int16_t x605B_shutdownOptionCode;
        int16_t x605C_disableOperationOptionCode;
        int16_t x605E_faultReactionOptionCode;
        int8_t x6060_modesOfOperation;
        uint32_t x6065_followingErrorWindow;
        uint16_t x6066_followingErrorTimeOut;
        uint32_t x6067_positionWindow;
        uint16_t x6068_positionWindowTime;
        int16_t x6071_targetTorque;
        int32_t x607A_targetPosition;
        uint8_t x607B_positionRangeLimit_sub0;
        int32_t x607B_positionRangeLimit[OD_CNT_ARR_607B];
        uint8_t x607D_softwarePositionLimit_sub0;
        int32_t x607D_softwarePositionLimit[OD_CNT_ARR_607D];
        uint32_t x6081_profileVelocity;
        uint32_t x6083_profileAcceleration;
        uint32_t x6084_profileDeceleration;
        uint32_t x6085_quickStopDeceleration;
        int16_t x6086_motionProfileType;
        int8_t x6098_homingMethod;
        uint8_t x6099_homingSpeeds_sub0;
        uint32_t x6099_homingSpeeds[OD_CNT_ARR_6099];
        uint32_t x609A_homingAcceleration;
        uint32_t x60A8_SIUnitPosition;
        uint32_t x60A9_SIUnitVelocity;
        uint32_t x60AA_SIUnitAcceleration;
        int32_t x60B0_positionOffset;
        int32_t x60B1_velocityOffset;
        int16_t x60B2_torqueOffset;
        uint16_t x60B8_touchProbeFunction;
        struct {
            uint8_t highestSub_indexSupported;
            uint8_t interpolationTimePeriodValue;
            int8_t interpolationTimeIndex;
        } x60C2_interpolationTimePeriod;
        uint32_t x60C5_maxAcceleration;
        uint8_t x60D0_touchProbeSource_sub0;
        uint8_t x60E3_supportedHomingMethods_sub0;
        uint8_t x60FE_digitalOutputs_sub0;
        uint32_t x60FE_digitalOutputs[OD_CNT_ARR_60FE];
        int32_t x60FF_targetVelocity;
        uint16_t x6402_motorType;//
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
//#define OD_ENTRY_H1008 &OD->list[4]//
#define OD_ENTRY_H1010 &OD->list[6]
#define OD_ENTRY_H1011 &OD->list[7]
#define OD_ENTRY_H1012 &OD->list[8]
#define OD_ENTRY_H1014 &OD->list[9]
#define OD_ENTRY_H1015 &OD->list[10]
#define OD_ENTRY_H1016 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1019 &OD->list[14]
//#define OD_ENTRY_H1029 &OD->list[11]//
#define OD_ENTRY_H1200 &OD->list[15]
#define OD_ENTRY_H1280 &OD->list[16]
#define OD_ENTRY_H1400 &OD->list[17]
#define OD_ENTRY_H1401 &OD->list[18]
#define OD_ENTRY_H1402 &OD->list[19]
#define OD_ENTRY_H1403 &OD->list[20]
#define OD_ENTRY_H1600 &OD->list[21]
#define OD_ENTRY_H1601 &OD->list[22]
#define OD_ENTRY_H1602 &OD->list[23]
#define OD_ENTRY_H1603 &OD->list[24]
#define OD_ENTRY_H1800 &OD->list[25]
#define OD_ENTRY_H1801 &OD->list[26]
#define OD_ENTRY_H1802 &OD->list[27]
#define OD_ENTRY_H1803 &OD->list[28]
#define OD_ENTRY_H1A00 &OD->list[29]
#define OD_ENTRY_H1A01 &OD->list[30]
#define OD_ENTRY_H1A02 &OD->list[31]
#define OD_ENTRY_H1A03 &OD->list[32]
//
#define OD_ENTRY_H1F50 &OD->list[29]
#define OD_ENTRY_H1F51 &OD->list[30]
#define OD_ENTRY_H1F56 &OD->list[31]
#define OD_ENTRY_H1F57 &OD->list[32]
#define OD_ENTRY_H2000 &OD->list[33]
#define OD_ENTRY_H2001 &OD->list[34]
#define OD_ENTRY_H2006 &OD->list[35]
#define OD_ENTRY_H200A &OD->list[36]
#define OD_ENTRY_H2010 &OD->list[37]
#define OD_ENTRY_H2011 &OD->list[38]
#define OD_ENTRY_H2100 &OD->list[39]
#define OD_ENTRY_H210C &OD->list[40]
#define OD_ENTRY_H2200 &OD->list[41]
#define OD_ENTRY_H2201 &OD->list[42]
#define OD_ENTRY_H2EC0 &OD->list[43]
#define OD_ENTRY_H3000 &OD->list[44]
#define OD_ENTRY_H3001 &OD->list[45]
#define OD_ENTRY_H3002 &OD->list[46]
#define OD_ENTRY_H3003 &OD->list[47]
#define OD_ENTRY_H3012 &OD->list[48]
#define OD_ENTRY_H30A0 &OD->list[49]
#define OD_ENTRY_H30A1 &OD->list[50]
#define OD_ENTRY_H30A2 &OD->list[51]
#define OD_ENTRY_H30A3 &OD->list[52]
#define OD_ENTRY_H30A4 &OD->list[53]
#define OD_ENTRY_H30B0 &OD->list[54]
#define OD_ENTRY_H30B1 &OD->list[55]
#define OD_ENTRY_H30B2 &OD->list[56]
#define OD_ENTRY_H30B5 &OD->list[57]
#define OD_ENTRY_H30D0 &OD->list[58]
#define OD_ENTRY_H30D1 &OD->list[59]
#define OD_ENTRY_H30D2 &OD->list[60]
#define OD_ENTRY_H30D3 &OD->list[61]
#define OD_ENTRY_H30E0 &OD->list[62]
#define OD_ENTRY_H3141 &OD->list[63]
#define OD_ENTRY_H3142 &OD->list[64]
#define OD_ENTRY_H3150 &OD->list[65]
#define OD_ENTRY_H3151 &OD->list[66]
#define OD_ENTRY_H3158 &OD->list[67]
#define OD_ENTRY_H3160 &OD->list[68]
#define OD_ENTRY_H3161 &OD->list[69]
#define OD_ENTRY_H3162 &OD->list[70]
#define OD_ENTRY_H3163 &OD->list[71]
#define OD_ENTRY_H3170 &OD->list[72]
#define OD_ENTRY_H3171 &OD->list[73]
#define OD_ENTRY_H31E0 &OD->list[74]
#define OD_ENTRY_H31E1 &OD->list[75]
#define OD_ENTRY_H31E2 &OD->list[76]
#define OD_ENTRY_H31E4 &OD->list[77]
#define OD_ENTRY_H31E5 &OD->list[78]
#define OD_ENTRY_H31E6 &OD->list[79]
#define OD_ENTRY_H31E7 &OD->list[80]
#define OD_ENTRY_H31E8 &OD->list[81]
#define OD_ENTRY_H31E9 &OD->list[82]
#define OD_ENTRY_H3200 &OD->list[83]
#define OD_ENTRY_H3201 &OD->list[84]
#define OD_ENTRY_H3203 &OD->list[85]
#define OD_ENTRY_H3240 &OD->list[86]
#define OD_ENTRY_H3241 &OD->list[87]
#define OD_ENTRY_H3248 &OD->list[88]
#define OD_ENTRY_H3249 &OD->list[89]
#define OD_ENTRY_H324B &OD->list[90]
#define OD_ENTRY_H324C &OD->list[91]
#define OD_ENTRY_H6007 &OD->list[92]
#define OD_ENTRY_H603F &OD->list[93]
#define OD_ENTRY_H6040 &OD->list[94]
#define OD_ENTRY_H6041 &OD->list[95]
#define OD_ENTRY_H605A &OD->list[96]
#define OD_ENTRY_H605B &OD->list[97]
#define OD_ENTRY_H605C &OD->list[98]
#define OD_ENTRY_H605E &OD->list[99]
#define OD_ENTRY_H6060 &OD->list[100]
#define OD_ENTRY_H6061 &OD->list[101]
#define OD_ENTRY_H6062 &OD->list[102]
#define OD_ENTRY_H6064 &OD->list[103]
#define OD_ENTRY_H6065 &OD->list[104]
#define OD_ENTRY_H6066 &OD->list[105]
#define OD_ENTRY_H6067 &OD->list[106]
#define OD_ENTRY_H6068 &OD->list[107]
#define OD_ENTRY_H606B &OD->list[108]
#define OD_ENTRY_H606C &OD->list[109]
#define OD_ENTRY_H6071 &OD->list[110]
#define OD_ENTRY_H6076 &OD->list[111]
#define OD_ENTRY_H6077 &OD->list[112]
#define OD_ENTRY_H607A &OD->list[113]
#define OD_ENTRY_H607B &OD->list[114]
#define OD_ENTRY_H607D &OD->list[115]
#define OD_ENTRY_H607F &OD->list[116]
#define OD_ENTRY_H6080 &OD->list[117]
#define OD_ENTRY_H6081 &OD->list[118]
#define OD_ENTRY_H6083 &OD->list[119]
#define OD_ENTRY_H6084 &OD->list[120]
#define OD_ENTRY_H6085 &OD->list[121]
#define OD_ENTRY_H6086 &OD->list[122]
#define OD_ENTRY_H6098 &OD->list[123]
#define OD_ENTRY_H6099 &OD->list[124]
#define OD_ENTRY_H609A &OD->list[125]
#define OD_ENTRY_H60A8 &OD->list[126]
#define OD_ENTRY_H60A9 &OD->list[127]
#define OD_ENTRY_H60AA &OD->list[128]
#define OD_ENTRY_H60B0 &OD->list[129]
#define OD_ENTRY_H60B1 &OD->list[130]
#define OD_ENTRY_H60B2 &OD->list[131]
#define OD_ENTRY_H60B8 &OD->list[132]
#define OD_ENTRY_H60B9 &OD->list[133]
#define OD_ENTRY_H60BA &OD->list[134]
#define OD_ENTRY_H60BB &OD->list[135]
#define OD_ENTRY_H60C2 &OD->list[136]
#define OD_ENTRY_H60C5 &OD->list[137]
#define OD_ENTRY_H60D0 &OD->list[138]
#define OD_ENTRY_H60D5 &OD->list[139]
#define OD_ENTRY_H60D6 &OD->list[140]
#define OD_ENTRY_H60E3 &OD->list[141]
#define OD_ENTRY_H60F4 &OD->list[142]
#define OD_ENTRY_H60FD &OD->list[143]
#define OD_ENTRY_H60FE &OD->list[144]
#define OD_ENTRY_H60FF &OD->list[145]
#define OD_ENTRY_H6402 &OD->list[146]
#define OD_ENTRY_H6502 &OD->list[147]

//

/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
//#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[4]
#define OD_ENTRY_H1010_storeParameters &OD->list[6]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[7]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[8]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[9]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[10]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identity &OD->list[13]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[14]
//#define OD_ENTRY_H1029_errorBehavior &OD->list[11]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[15]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[16]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[21]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[22]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[23]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[32]
//
#define OD_ENTRY_H1F50_programData &OD->list[29]
#define OD_ENTRY_H1F51_programControl &OD->list[30]
#define OD_ENTRY_H1F56_programSoftwareIdentification &OD->list[31]
#define OD_ENTRY_H1F57_flashStatusIdentification &OD->list[32]
#define OD_ENTRY_H2000_node_ID &OD->list[33]
#define OD_ENTRY_H2001_CANBitRate &OD->list[34]
#define OD_ENTRY_H2006_USBFrameTimeout &OD->list[35]
#define OD_ENTRY_H200A_CANBitRateDisplay &OD->list[36]
#define OD_ENTRY_H2010_activeFieldbus &OD->list[37]
#define OD_ENTRY_H2011_activeControllerType &OD->list[38]
#define OD_ENTRY_H2100_additionalIdentity &OD->list[39]
#define OD_ENTRY_H210C_customPersistentMemory &OD->list[40]
#define OD_ENTRY_H2200_powerSupply &OD->list[41]
#define OD_ENTRY_H2201_powerSupplySupervision &OD->list[42]
#define OD_ENTRY_H2EC0_internalDeviceControl &OD->list[43]
#define OD_ENTRY_H3000_axisConfiguration &OD->list[44]
#define OD_ENTRY_H3001_motorData &OD->list[45]
#define OD_ENTRY_H3002_electricalSystemParameters &OD->list[46]
#define OD_ENTRY_H3003_gearConfiguration &OD->list[47]
#define OD_ENTRY_H3012_SSIAbsoluteEncoder &OD->list[48]
#define OD_ENTRY_H30A0_currentControlParameterSet &OD->list[49]
#define OD_ENTRY_H30A1_positionControlParameterSet &OD->list[50]
#define OD_ENTRY_H30A2_velocityControlParameterSet &OD->list[51]
#define OD_ENTRY_H30A3_velocityObserverParameterSet &OD->list[52]
#define OD_ENTRY_H30A4_internalVelocityFilterParameterSet &OD->list[53]
#define OD_ENTRY_H30B0_homePosition &OD->list[54]
#define OD_ENTRY_H30B1_homeOffsetMoveDistance &OD->list[55]
#define OD_ENTRY_H30B2_currentThresholdForHomingMode &OD->list[56]
#define OD_ENTRY_H30B5_internalHomingData &OD->list[57]
#define OD_ENTRY_H30D0_currentDemandValue &OD->list[58]
#define OD_ENTRY_H30D1_currentActualValues &OD->list[59]
#define OD_ENTRY_H30D2_torqueActualValues &OD->list[60]
#define OD_ENTRY_H30D3_velocityActualValues &OD->list[61]
#define OD_ENTRY_H30E0_standstillWindowConfiguration &OD->list[62]
#define OD_ENTRY_H3141_digitalInputProperties &OD->list[63]
#define OD_ENTRY_H3142_configurationOfDigitalInputs &OD->list[64]
#define OD_ENTRY_H3150_digitalOutputProperties &OD->list[65]
#define OD_ENTRY_H3151_configurationOfDigitalOutputs &OD->list[66]
#define OD_ENTRY_H3158_holdingBrakeParameters &OD->list[67]
#define OD_ENTRY_H3160_analogInputProperties &OD->list[68]
#define OD_ENTRY_H3161_configurationOfAnalogInputs &OD->list[69]
#define OD_ENTRY_H3162_analogInputGeneralPurpose &OD->list[70]
#define OD_ENTRY_H3163_analogInputAdjustment &OD->list[71]
#define OD_ENTRY_H3170_analogInputCurrentSetValueProperties &OD->list[72]
#define OD_ENTRY_H3171_analogInputVelocitySetValueProperties &OD->list[73]
#define OD_ENTRY_H31E0_internalDataRecorderVariableIndex &OD->list[74]
#define OD_ENTRY_H31E1_internalDataRecorderConfiguration &OD->list[75]
#define OD_ENTRY_H31E2_internalDataRecorderTrigger &OD->list[76]
#define OD_ENTRY_H31E4_internalDataRecorderControl &OD->list[77]
#define OD_ENTRY_H31E5_internalDataRecorderData &OD->list[78]
#define OD_ENTRY_H31E6_internalDataRecorderBufferVariable1 &OD->list[79]
#define OD_ENTRY_H31E7_internalDataRecorderBufferVariable2 &OD->list[80]
#define OD_ENTRY_H31E8_internalDataRecorderBufferVariable3 &OD->list[81]
#define OD_ENTRY_H31E9_internalDataRecorderBufferVariable4 &OD->list[82]
#define OD_ENTRY_H3200_powerLimitation &OD->list[83]
#define OD_ENTRY_H3201_thermalOverloadProtection &OD->list[84]
#define OD_ENTRY_H3203_motorControl &OD->list[85]
#define OD_ENTRY_H3240_internalTestObject &OD->list[86]
#define OD_ENTRY_H3241_internalMotorControl &OD->list[87]
#define OD_ENTRY_H3248_internalConfigurationElectricalSystemTuning &OD->list[88]
#define OD_ENTRY_H3249_internalParametersElectricalSystemTuning &OD->list[89]
#define OD_ENTRY_H324B_internalConfigurationMechanicalSystemTuning &OD->list[90]
#define OD_ENTRY_H324C_internalParametersMechanicalSystemTuning &OD->list[91]
#define OD_ENTRY_H6007_abortConnectionOptionCode &OD->list[92]
#define OD_ENTRY_H603F_errorCode &OD->list[93]
#define OD_ENTRY_H6040_controlword &OD->list[94]
#define OD_ENTRY_H6041_statusword &OD->list[95]
#define OD_ENTRY_H605A_quickStopOptionCode &OD->list[96]
#define OD_ENTRY_H605B_shutdownOptionCode &OD->list[97]
#define OD_ENTRY_H605C_disableOperationOptionCode &OD->list[98]
#define OD_ENTRY_H605E_faultReactionOptionCode &OD->list[99]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[100]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[101]
#define OD_ENTRY_H6062_positionDemandValue &OD->list[102]
#define OD_ENTRY_H6064_positionActualValue &OD->list[103]
#define OD_ENTRY_H6065_followingErrorWindow &OD->list[104]
#define OD_ENTRY_H6066_followingErrorTimeOut &OD->list[105]
#define OD_ENTRY_H6067_positionWindow &OD->list[106]
#define OD_ENTRY_H6068_positionWindowTime &OD->list[107]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[108]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[109]
#define OD_ENTRY_H6071_targetTorque &OD->list[110]
#define OD_ENTRY_H6076_motorRatedTorque &OD->list[111]
#define OD_ENTRY_H6077_torqueActualValue &OD->list[112]
#define OD_ENTRY_H607A_targetPosition &OD->list[113]
#define OD_ENTRY_H607B_positionRangeLimit &OD->list[114]
#define OD_ENTRY_H607D_softwarePositionLimit &OD->list[115]
#define OD_ENTRY_H607F_maxProfileVelocity &OD->list[116]
#define OD_ENTRY_H6080_maxMotorSpeed &OD->list[117]
#define OD_ENTRY_H6081_profileVelocity &OD->list[118]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[119]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[120]
#define OD_ENTRY_H6085_quickStopDeceleration &OD->list[121]
#define OD_ENTRY_H6086_motionProfileType &OD->list[122]
#define OD_ENTRY_H6098_homingMethod &OD->list[123]
#define OD_ENTRY_H6099_homingSpeeds &OD->list[124]
#define OD_ENTRY_H609A_homingAcceleration &OD->list[125]
#define OD_ENTRY_H60A8_SIUnitPosition &OD->list[126]
#define OD_ENTRY_H60A9_SIUnitVelocity &OD->list[127]
#define OD_ENTRY_H60AA_SIUnitAcceleration &OD->list[128]
#define OD_ENTRY_H60B0_positionOffset &OD->list[129]
#define OD_ENTRY_H60B1_velocityOffset &OD->list[130]
#define OD_ENTRY_H60B2_torqueOffset &OD->list[131]
#define OD_ENTRY_H60B8_touchProbeFunction &OD->list[132]
#define OD_ENTRY_H60B9_touchProbeStatus &OD->list[133]
#define OD_ENTRY_H60BA_touchProbe1PositiveEdge &OD->list[134]
#define OD_ENTRY_H60BB_touchProbe1NegativeEdge &OD->list[135]
#define OD_ENTRY_H60C2_interpolationTimePeriod &OD->list[136]
#define OD_ENTRY_H60C5_maxAcceleration &OD->list[137]
#define OD_ENTRY_H60D0_touchProbeSource &OD->list[138]
#define OD_ENTRY_H60D5_touchProbe1PositiveEdgeCounter &OD->list[139]
#define OD_ENTRY_H60D6_touchProbe1NegativeEdgeCounter &OD->list[140]
#define OD_ENTRY_H60E3_supportedHomingMethods &OD->list[141]
#define OD_ENTRY_H60F4_followingErrorActualValue &OD->list[142]
#define OD_ENTRY_H60FD_digitalInputs &OD->list[143]
#define OD_ENTRY_H60FE_digitalOutputs &OD->list[144]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[145]
#define OD_ENTRY_H6402_motorType &OD->list[146]
#define OD_ENTRY_H6502_supportedDriveModes &OD->list[147]
//

/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
