/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00040192,
    .x1001_errorRegister = 0x00,
    .x1003_predefinedErrorField_sub0 = 0x00,
    .x1003_predefinedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1005_COB_ID_SYNC = 0x00000080,
    .x1008_manufacturerDeviceName = {'F', 'D', '1', 0},
    .x1009_manufacturerHardwareVersion = {'V', '1', '.', '2', 0},
    .x100A_manufacturerSoftwareVersion = {'V', '9', '.', '0', '8', 0},
    .x100C_guardTime = 0x0000,
    .x100D_lifeTimeFactor = 0x00,
    .x1010_storeParameterField_sub0 = 0x01,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1016_consumerHeartbeatTime_sub0 = 0x01,
    .x1016_consumerHeartbeatTime = {0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04,
        .vendorId = 0x00000531,
        .serialNumber = 0x00000000
    },
    .x1400_receivePDO_CommunicationParameter0 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000200,
        .transmissionType = 0x00
    },
    .x1401_receivePDO_CommunicationParameter1 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000300,
        .transmissionType = 0x00
    },
    .x1402_receivePDO_CommunicationParameter2 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000400,
        .transmissionType = 0x00
    },
    .x1403_receivePDO_CommunicationParameter3 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000500,
        .transmissionType = 0x00
    },
    .x1600_receivePDO_MappingParameter0 = {
        .numberOfEntries = 0x01,
        .PDO_MappingEntry = 0x60400010
    },
    .x1601_receivePDO_MappingParameter1 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x60600008,
        .PDO_MappingEntry_2 = 0x60400010
    },
    .x1602_receivePDO_MappingParameter2 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x607A0020,
        .PDO_MappingEntry_2 = 0x60400010
    },
    .x1603_receivePDO_MappingParameter3 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x60FF0020,
        .PDO_MappingEntry_2 = 0x60400010
    },
    .x1800_transmitPDO_CommunicationParameter0 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000180,
        .transmissionType = 0x00,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000
    },
    .x1801_transmitPDO_CommunicationParameter1 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000280,
        .transmissionType = 0x00,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000
    },
    .x1802_transmitPDO_CommunicationParameter2 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000380,
        .transmissionType = 0x00,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000
    },
    .x1803_transmitPDO_CommunicationParameter3 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000480,
        .transmissionType = 0x00,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000
    },
    .x1A00_transmitPDO_MappingParameter0 = {
        .numberOfEntries = 0x01,
        .PDO_MappingEntry = 0x60410010
    },
    .x1A01_transmitPDO_MappingParameter1 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x60610008,
        .PDO_MappingEntry_2 = 0x60410010
    },
    .x1A02_transmitPDO_MappingParameter2 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x60630020,
        .PDO_MappingEntry_2 = 0x60410010
    },
    .x1A03_transmitPDO_MappingParameter3 = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry = 0x606C0020,
        .PDO_MappingEntry_2 = 0x60410010
    },
    .x1F50_downloadProgramData_sub0 = 0x01,
    .x1F52_verifyApplicationSoftware_sub0 = 0x02,
    .x1F52_verifyApplicationSoftware = {0x0000383C, 0x00000000},
    .x2006_modbusRegistersArray2_sub0 = 0x6A,
    .x6060_modes_of_operation = 0,
    .x607C_home_offset = 0,
    .x607D_software_position_limit_sub0 = 0x02,
    .x607F_max_profile_velocity = 0x000493E0,
    .x6086_motion_profile_type = 0,
    .x6098_homing_method = 0,
    .x6099_homing_speeds_sub0 = 0x02,
    .x6099_homing_speeds = {0x00000000, 0x00000000},
    .x60C0_interpolation_sub_mode_select = 0,
    .x60C1_interpolation_data_record_sub0 = 0x01,
    .x60C2_interpolation_time_period = {
        .interpolation_time_period_number_of_entries = 0x02,
        .interpolation_time_period_Interpolation_time_units = 0x01,
        .interpolation_time_period_Interpolation_time_index = -3
    },
    .x60C4_interpolation_data_configuration = {
        .interpolation_data_configuration_number_of_entries = 0x06,
        .interpolation_data_configuration_Maximum_buffer_size = 0x00000020,
        .interpolation_data_configuration_Actual_buffer_size = 0x00000000,
        .interpolation_data_configuration_Buffer_organization = 0x00,
        .interpolation_data_configuration_Buffer_position = 0x0000,
        .interpolation_data_configuration_Size_of_data_record = 0x01,
        .value_Description_Buffer_clear = 0x00
    },
    .x60FD_digital_inputs = 0x00000000,
    .x6402_motor_type = 0x0009,
    .x6502_supported_drive_modes = 0x00000065
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_predefinedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNC;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_100C_guardTime;
    OD_obj_var_t o_100D_lifeTimeFactor;
    OD_obj_array_t o_1010_storeParameterField;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_record_t o_1400_receivePDO_CommunicationParameter0[3];
    OD_obj_record_t o_1401_receivePDO_CommunicationParameter1[3];
    OD_obj_record_t o_1402_receivePDO_CommunicationParameter2[3];
    OD_obj_record_t o_1403_receivePDO_CommunicationParameter3[3];
    OD_obj_record_t o_1600_receivePDO_MappingParameter0[9];
    OD_obj_record_t o_1601_receivePDO_MappingParameter1[9];
    OD_obj_record_t o_1602_receivePDO_MappingParameter2[9];
    OD_obj_record_t o_1603_receivePDO_MappingParameter3[9];
    OD_obj_record_t o_1800_transmitPDO_CommunicationParameter0[6];
    OD_obj_record_t o_1801_transmitPDO_CommunicationParameter1[6];
    OD_obj_record_t o_1802_transmitPDO_CommunicationParameter2[6];
    OD_obj_record_t o_1803_transmitPDO_CommunicationParameter3[6];
    OD_obj_record_t o_1A00_transmitPDO_MappingParameter0[9];
    OD_obj_record_t o_1A01_transmitPDO_MappingParameter1[9];
    OD_obj_record_t o_1A02_transmitPDO_MappingParameter2[9];
    OD_obj_record_t o_1A03_transmitPDO_MappingParameter3[9];
    OD_obj_array_t o_1F50_downloadProgramData;
    OD_obj_array_t o_1F52_verifyApplicationSoftware;
    OD_obj_var_t o_2003_deltaStopSteps;
    OD_obj_array_t o_2005_modbusRegistersArray1;
    OD_obj_array_t o_2006_modbusRegistersArray2;
    OD_obj_var_t o_603F_errorCode;
    OD_obj_var_t o_6040_controlWord;
    OD_obj_var_t o_6041_statusWord;
    OD_obj_var_t o_6060_modes_of_operation;
    OD_obj_var_t o_6061_modes_of_operation_display;
    OD_obj_var_t o_6062_position_demand_value;
    OD_obj_var_t o_6063_position_actual_value;
    OD_obj_var_t o_6064_position_actual_value;
    OD_obj_var_t o_6065_following_error_window;
    OD_obj_var_t o_6069_velocity_sensor_actual_value;
    OD_obj_var_t o_606B_velocity_demand_value;
    OD_obj_var_t o_606C_velocity_actual_value;
    OD_obj_var_t o_607A_target_position;
    OD_obj_var_t o_607C_home_offset;
    OD_obj_array_t o_607D_software_position_limit;
    OD_obj_var_t o_607F_max_profile_velocity;
    OD_obj_var_t o_6081_profile_velocity;
    OD_obj_var_t o_6083_profile_acceleration;
    OD_obj_var_t o_6084_profile_deceleration;
    OD_obj_var_t o_6086_motion_profile_type;
    OD_obj_var_t o_6098_homing_method;
    OD_obj_array_t o_6099_homing_speeds;
    OD_obj_var_t o_609A_homing_acceleration;
    OD_obj_var_t o_60C0_interpolation_sub_mode_select;
    OD_obj_array_t o_60C1_interpolation_data_record;
    OD_obj_record_t o_60C2_interpolation_time_period[3];
    OD_obj_record_t o_60C4_interpolation_data_configuration[7];
    OD_obj_var_t o_60F4_following_error_actual_value;
    OD_obj_var_t o_60FD_digital_inputs;
    OD_obj_var_t o_60FF_target_velocity;
    OD_obj_var_t o_6402_motor_type;
    OD_obj_var_t o_6502_supported_drive_modes;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1003_predefinedErrorField = {
        .dataOrig0 = &OD_RAM.x1003_predefinedErrorField_sub0,
        .dataOrig = &OD_RAM.x1003_predefinedErrorField[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNC = {
        .dataOrig = &OD_RAM.x1005_COB_ID_SYNC,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_RAM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 4
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 5
    },
    .o_100C_guardTime = {
        .dataOrig = &OD_RAM.x100C_guardTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_100D_lifeTimeFactor = {
        .dataOrig = &OD_RAM.x100D_lifeTimeFactor,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1010_storeParameterField = {
        .dataOrig0 = &OD_RAM.x1010_storeParameterField_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_RAM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_RAM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_RAM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.vendorId,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO_CommunicationParameter0 = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter0.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter0.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter0.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1402_receivePDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1402_receivePDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1403_receivePDO_CommunicationParameter3 = {
        {
            .dataOrig = &OD_RAM.x1403_receivePDO_CommunicationParameter3.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO_CommunicationParameter3.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO_CommunicationParameter3.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO_MappingParameter0 = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO_MappingParameter0.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO_MappingParameter0.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter1.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter1.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_receivePDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1602_receivePDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO_MappingParameter2.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO_MappingParameter2.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_receivePDO_MappingParameter3 = {
        {
            .dataOrig = &OD_RAM.x1603_receivePDO_MappingParameter3.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO_MappingParameter3.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO_MappingParameter3.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO_CommunicationParameter0 = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter0.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter0.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter0.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter0.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter0.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1801_transmitPDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter1.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter1.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1802_transmitPDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO_CommunicationParameter2.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO_CommunicationParameter2.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1803_transmitPDO_CommunicationParameter3 = {
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO_CommunicationParameter3.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO_CommunicationParameter3.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO_CommunicationParameter3.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO_CommunicationParameter3.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO_CommunicationParameter3.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1A00_transmitPDO_MappingParameter0 = {
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO_MappingParameter0.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO_MappingParameter0.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_transmitPDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO_MappingParameter1.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO_MappingParameter1.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_transmitPDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO_MappingParameter2.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO_MappingParameter2.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_transmitPDO_MappingParameter3 = {
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO_MappingParameter3.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO_MappingParameter3.PDO_MappingEntry,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO_MappingParameter3.PDO_MappingEntry_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1F50_downloadProgramData = {
        .dataOrig0 = &OD_RAM.x1F50_downloadProgramData_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1F52_verifyApplicationSoftware = {
        .dataOrig0 = &OD_RAM.x1F52_verifyApplicationSoftware_sub0,
        .dataOrig = &OD_RAM.x1F52_verifyApplicationSoftware[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2003_deltaStopSteps = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2005_modbusRegistersArray1 = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2006_modbusRegistersArray2 = {
        .dataOrig0 = &OD_RAM.x2006_modbusRegistersArray2_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_603F_errorCode = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6040_controlWord = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusWord = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modes_of_operation = {
        .dataOrig = &OD_RAM.x6060_modes_of_operation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6061_modes_of_operation_display = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6062_position_demand_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6063_position_actual_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6064_position_actual_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6065_following_error_window = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6069_velocity_sensor_actual_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606B_velocity_demand_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocity_actual_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607A_target_position = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607C_home_offset = {
        .dataOrig = &OD_RAM.x607C_home_offset,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607D_software_position_limit = {
        .dataOrig0 = &OD_RAM.x607D_software_position_limit_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607F_max_profile_velocity = {
        .dataOrig = &OD_RAM.x607F_max_profile_velocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6081_profile_velocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profile_acceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6084_profile_deceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6086_motion_profile_type = {
        .dataOrig = &OD_RAM.x6086_motion_profile_type,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6098_homing_method = {
        .dataOrig = &OD_RAM.x6098_homing_method,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6099_homing_speeds = {
        .dataOrig0 = &OD_RAM.x6099_homing_speeds_sub0,
        .dataOrig = &OD_RAM.x6099_homing_speeds[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_609A_homing_acceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60C0_interpolation_sub_mode_select = {
        .dataOrig = &OD_RAM.x60C0_interpolation_sub_mode_select,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_60C1_interpolation_data_record = {
        .dataOrig0 = &OD_RAM.x60C1_interpolation_data_record_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_60C2_interpolation_time_period = {
        {
            .dataOrig = &OD_RAM.x60C2_interpolation_time_period.interpolation_time_period_number_of_entries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C2_interpolation_time_period.interpolation_time_period_Interpolation_time_units,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C2_interpolation_time_period.interpolation_time_period_Interpolation_time_index,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_60C4_interpolation_data_configuration = {
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_number_of_entries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_Maximum_buffer_size,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_Actual_buffer_size,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_Buffer_organization,
            .subIndex = 3,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_Buffer_position,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.interpolation_data_configuration_Size_of_data_record,
            .subIndex = 5,
            .attribute = ODA_SDO_W,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolation_data_configuration.value_Description_Buffer_clear,
            .subIndex = 6,
            .attribute = ODA_SDO_W,
            .dataLength = 1
        }
    },
    .o_60F4_following_error_actual_value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_60FD_digital_inputs = {
        .dataOrig = &OD_RAM.x60FD_digital_inputs,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FF_target_velocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6402_motor_type = {
        .dataOrig = &OD_RAM.x6402_motor_type,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6502_supported_drive_modes = {
        .dataOrig = &OD_RAM.x6502_supported_drive_modes,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x09, ODT_ARR, &ODObjs.o_1003_predefinedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNC, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x100C, 0x01, ODT_VAR, &ODObjs.o_100C_guardTime, NULL},
    {0x100D, 0x01, ODT_VAR, &ODObjs.o_100D_lifeTimeFactor, NULL},
    {0x1010, 0x02, ODT_ARR, &ODObjs.o_1010_storeParameterField, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1016, 0x02, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO_CommunicationParameter0, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO_CommunicationParameter1, NULL},
    {0x1402, 0x03, ODT_REC, &ODObjs.o_1402_receivePDO_CommunicationParameter2, NULL},
    {0x1403, 0x03, ODT_REC, &ODObjs.o_1403_receivePDO_CommunicationParameter3, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_receivePDO_MappingParameter0, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_receivePDO_MappingParameter1, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_receivePDO_MappingParameter2, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_receivePDO_MappingParameter3, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO_CommunicationParameter0, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO_CommunicationParameter1, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_transmitPDO_CommunicationParameter2, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_transmitPDO_CommunicationParameter3, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_transmitPDO_MappingParameter0, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_transmitPDO_MappingParameter1, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_transmitPDO_MappingParameter2, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_transmitPDO_MappingParameter3, NULL},
    {0x1F50, 0x02, ODT_ARR, &ODObjs.o_1F50_downloadProgramData, NULL},
    {0x1F52, 0x03, ODT_ARR, &ODObjs.o_1F52_verifyApplicationSoftware, NULL},
    {0x2003, 0x01, ODT_VAR, &ODObjs.o_2003_deltaStopSteps, NULL},
    {0x2005, 0xFF, ODT_ARR, &ODObjs.o_2005_modbusRegistersArray1, NULL},
    {0x2006, 0x6B, ODT_ARR, &ODObjs.o_2006_modbusRegistersArray2, NULL},
    {0x603F, 0x01, ODT_VAR, &ODObjs.o_603F_errorCode, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlWord, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusWord, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modes_of_operation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_modes_of_operation_display, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_position_demand_value, NULL},
    {0x6063, 0x01, ODT_VAR, &ODObjs.o_6063_position_actual_value, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_position_actual_value, NULL},
    {0x6065, 0x01, ODT_VAR, &ODObjs.o_6065_following_error_window, NULL},
    {0x6069, 0x01, ODT_VAR, &ODObjs.o_6069_velocity_sensor_actual_value, NULL},
    {0x606B, 0x01, ODT_VAR, &ODObjs.o_606B_velocity_demand_value, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocity_actual_value, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_target_position, NULL},
    {0x607C, 0x01, ODT_VAR, &ODObjs.o_607C_home_offset, NULL},
    {0x607D, 0x03, ODT_ARR, &ODObjs.o_607D_software_position_limit, NULL},
    {0x607F, 0x01, ODT_VAR, &ODObjs.o_607F_max_profile_velocity, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profile_velocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profile_acceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_profile_deceleration, NULL},
    {0x6086, 0x01, ODT_VAR, &ODObjs.o_6086_motion_profile_type, NULL},
    {0x6098, 0x01, ODT_VAR, &ODObjs.o_6098_homing_method, NULL},
    {0x6099, 0x03, ODT_ARR, &ODObjs.o_6099_homing_speeds, NULL},
    {0x609A, 0x01, ODT_VAR, &ODObjs.o_609A_homing_acceleration, NULL},
    {0x60C0, 0x01, ODT_VAR, &ODObjs.o_60C0_interpolation_sub_mode_select, NULL},
    {0x60C1, 0x02, ODT_ARR, &ODObjs.o_60C1_interpolation_data_record, NULL},
    {0x60C2, 0x03, ODT_REC, &ODObjs.o_60C2_interpolation_time_period, NULL},
    {0x60C4, 0x07, ODT_REC, &ODObjs.o_60C4_interpolation_data_configuration, NULL},
    {0x60F4, 0x01, ODT_VAR, &ODObjs.o_60F4_following_error_actual_value, NULL},
    {0x60FD, 0x01, ODT_VAR, &ODObjs.o_60FD_digital_inputs, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_target_velocity, NULL},
    {0x6402, 0x01, ODT_VAR, &ODObjs.o_6402_motor_type, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_supported_drive_modes, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
