/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: auxindPic.xdd
        File Version: 1

        Created:      2023-10-20 9:54:00 AM
        Created By:   MS
        Modified:     2025-04-07 1:05:49 PM
        Modified By:  MS

    Device Info:
        Vendor Name:  MAE Ametek
        Vendor ID:    1329
        Product Name: FD1.1GA
        Product ID:   0x0001

        Description:  FD1 stepper motor drive
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_STORAGE 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 8
#define OD_CNT_ARR_1010 1
#define OD_CNT_ARR_1016 1
#define OD_CNT_ARR_1F50 1
#define OD_CNT_ARR_1F52 2
#define OD_CNT_ARR_2005 254
#define OD_CNT_ARR_2006 106
#define OD_CNT_ARR_607D 2
#define OD_CNT_ARR_6099 2
#define OD_CNT_ARR_60C1 1


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint8_t x1003_predefinedErrorField_sub0;
    uint32_t x1003_predefinedErrorField[OD_CNT_ARR_1003];
    uint32_t x1005_COB_ID_SYNC;
    char x1008_manufacturerDeviceName[4];
    char x1009_manufacturerHardwareVersion[5];
    char x100A_manufacturerSoftwareVersion[6];
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint8_t x1010_storeParameterField_sub0;
    uint32_t x1014_COB_ID_EMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorId;
        uint32_t serialNumber;
    } x1018_identityObject;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1400_receivePDO_CommunicationParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1401_receivePDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1402_receivePDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1403_receivePDO_CommunicationParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
    } x1600_receivePDO_MappingParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1601_receivePDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1602_receivePDO_MappingParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1603_receivePDO_MappingParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
    } x1800_transmitPDO_CommunicationParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
    } x1801_transmitPDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
    } x1802_transmitPDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
    } x1803_transmitPDO_CommunicationParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
    } x1A00_transmitPDO_MappingParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1A01_transmitPDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1A02_transmitPDO_MappingParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry;
        uint32_t PDO_MappingEntry_2;
    } x1A03_transmitPDO_MappingParameter3;
    uint8_t x1F50_downloadProgramData_sub0;
    uint8_t x1F52_verifyApplicationSoftware_sub0;
    uint32_t x1F52_verifyApplicationSoftware[OD_CNT_ARR_1F52];
    uint8_t x2006_modbusRegistersArray2_sub0;
    int8_t x6060_modes_of_operation;
    int32_t x607C_home_offset;
    uint8_t x607D_software_position_limit_sub0;
    uint32_t x607F_max_profile_velocity;
    int16_t x6086_motion_profile_type;
    int8_t x6098_homing_method;
    uint8_t x6099_homing_speeds_sub0;
    uint32_t x6099_homing_speeds[OD_CNT_ARR_6099];
    int16_t x60C0_interpolation_sub_mode_select;
    uint8_t x60C1_interpolation_data_record_sub0;
    struct {
        uint8_t interpolation_time_period_number_of_entries;
        uint8_t interpolation_time_period_Interpolation_time_units;
        int8_t interpolation_time_period_Interpolation_time_index;
    } x60C2_interpolation_time_period;
    struct {
        uint8_t interpolation_data_configuration_number_of_entries;
        uint32_t interpolation_data_configuration_Maximum_buffer_size;
        uint32_t interpolation_data_configuration_Actual_buffer_size;
        uint8_t interpolation_data_configuration_Buffer_organization;
        uint16_t interpolation_data_configuration_Buffer_position;
        uint8_t interpolation_data_configuration_Size_of_data_record;
        uint8_t value_Description_Buffer_clear;
    } x60C4_interpolation_data_configuration;
    uint32_t x60FD_digital_inputs;
    uint16_t x6402_motor_type;
    uint32_t x6502_supported_drive_modes;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1008 &OD->list[4]
#define OD_ENTRY_H1009 &OD->list[5]
#define OD_ENTRY_H100A &OD->list[6]
#define OD_ENTRY_H100C &OD->list[7]
#define OD_ENTRY_H100D &OD->list[8]
#define OD_ENTRY_H1010 &OD->list[9]
#define OD_ENTRY_H1014 &OD->list[10]
#define OD_ENTRY_H1016 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1400 &OD->list[14]
#define OD_ENTRY_H1401 &OD->list[15]
#define OD_ENTRY_H1402 &OD->list[16]
#define OD_ENTRY_H1403 &OD->list[17]
#define OD_ENTRY_H1600 &OD->list[18]
#define OD_ENTRY_H1601 &OD->list[19]
#define OD_ENTRY_H1602 &OD->list[20]
#define OD_ENTRY_H1603 &OD->list[21]
#define OD_ENTRY_H1800 &OD->list[22]
#define OD_ENTRY_H1801 &OD->list[23]
#define OD_ENTRY_H1802 &OD->list[24]
#define OD_ENTRY_H1803 &OD->list[25]
#define OD_ENTRY_H1A00 &OD->list[26]
#define OD_ENTRY_H1A01 &OD->list[27]
#define OD_ENTRY_H1A02 &OD->list[28]
#define OD_ENTRY_H1A03 &OD->list[29]
#define OD_ENTRY_H1F50 &OD->list[30]
#define OD_ENTRY_H1F52 &OD->list[31]
#define OD_ENTRY_H2003 &OD->list[32]
#define OD_ENTRY_H2005 &OD->list[33]
#define OD_ENTRY_H2006 &OD->list[34]
#define OD_ENTRY_H603F &OD->list[35]
#define OD_ENTRY_H6040 &OD->list[36]
#define OD_ENTRY_H6041 &OD->list[37]
#define OD_ENTRY_H6060 &OD->list[38]
#define OD_ENTRY_H6061 &OD->list[39]
#define OD_ENTRY_H6062 &OD->list[40]
#define OD_ENTRY_H6063 &OD->list[41]
#define OD_ENTRY_H6064 &OD->list[42]
#define OD_ENTRY_H6065 &OD->list[43]
#define OD_ENTRY_H6069 &OD->list[44]
#define OD_ENTRY_H606B &OD->list[45]
#define OD_ENTRY_H606C &OD->list[46]
#define OD_ENTRY_H607A &OD->list[47]
#define OD_ENTRY_H607C &OD->list[48]
#define OD_ENTRY_H607D &OD->list[49]
#define OD_ENTRY_H607F &OD->list[50]
#define OD_ENTRY_H6081 &OD->list[51]
#define OD_ENTRY_H6083 &OD->list[52]
#define OD_ENTRY_H6084 &OD->list[53]
#define OD_ENTRY_H6086 &OD->list[54]
#define OD_ENTRY_H6098 &OD->list[55]
#define OD_ENTRY_H6099 &OD->list[56]
#define OD_ENTRY_H609A &OD->list[57]
#define OD_ENTRY_H60C0 &OD->list[58]
#define OD_ENTRY_H60C1 &OD->list[59]
#define OD_ENTRY_H60C2 &OD->list[60]
#define OD_ENTRY_H60C4 &OD->list[61]
#define OD_ENTRY_H60F4 &OD->list[62]
#define OD_ENTRY_H60FD &OD->list[63]
#define OD_ENTRY_H60FF &OD->list[64]
#define OD_ENTRY_H6402 &OD->list[65]
#define OD_ENTRY_H6502 &OD->list[66]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_predefinedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNC &OD->list[3]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[4]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[5]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[6]
#define OD_ENTRY_H100C_guardTime &OD->list[7]
#define OD_ENTRY_H100D_lifeTimeFactor &OD->list[8]
#define OD_ENTRY_H1010_storeParameterField &OD->list[9]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[10]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identityObject &OD->list[13]
#define OD_ENTRY_H1400_receivePDO_CommunicationParameter0 &OD->list[14]
#define OD_ENTRY_H1401_receivePDO_CommunicationParameter1 &OD->list[15]
#define OD_ENTRY_H1402_receivePDO_CommunicationParameter2 &OD->list[16]
#define OD_ENTRY_H1403_receivePDO_CommunicationParameter3 &OD->list[17]
#define OD_ENTRY_H1600_receivePDO_MappingParameter0 &OD->list[18]
#define OD_ENTRY_H1601_receivePDO_MappingParameter1 &OD->list[19]
#define OD_ENTRY_H1602_receivePDO_MappingParameter2 &OD->list[20]
#define OD_ENTRY_H1603_receivePDO_MappingParameter3 &OD->list[21]
#define OD_ENTRY_H1800_transmitPDO_CommunicationParameter0 &OD->list[22]
#define OD_ENTRY_H1801_transmitPDO_CommunicationParameter1 &OD->list[23]
#define OD_ENTRY_H1802_transmitPDO_CommunicationParameter2 &OD->list[24]
#define OD_ENTRY_H1803_transmitPDO_CommunicationParameter3 &OD->list[25]
#define OD_ENTRY_H1A00_transmitPDO_MappingParameter0 &OD->list[26]
#define OD_ENTRY_H1A01_transmitPDO_MappingParameter1 &OD->list[27]
#define OD_ENTRY_H1A02_transmitPDO_MappingParameter2 &OD->list[28]
#define OD_ENTRY_H1A03_transmitPDO_MappingParameter3 &OD->list[29]
#define OD_ENTRY_H1F50_downloadProgramData &OD->list[30]
#define OD_ENTRY_H1F52_verifyApplicationSoftware &OD->list[31]
#define OD_ENTRY_H2003_deltaStopSteps &OD->list[32]
#define OD_ENTRY_H2005_modbusRegistersArray1 &OD->list[33]
#define OD_ENTRY_H2006_modbusRegistersArray2 &OD->list[34]
#define OD_ENTRY_H603F_errorCode &OD->list[35]
#define OD_ENTRY_H6040_controlWord &OD->list[36]
#define OD_ENTRY_H6041_statusWord &OD->list[37]
#define OD_ENTRY_H6060_modes_of_operation &OD->list[38]
#define OD_ENTRY_H6061_modes_of_operation_display &OD->list[39]
#define OD_ENTRY_H6062_position_demand_value &OD->list[40]
#define OD_ENTRY_H6063_position_actual_value &OD->list[41]
#define OD_ENTRY_H6064_position_actual_value &OD->list[42]
#define OD_ENTRY_H6065_following_error_window &OD->list[43]
#define OD_ENTRY_H6069_velocity_sensor_actual_value &OD->list[44]
#define OD_ENTRY_H606B_velocity_demand_value &OD->list[45]
#define OD_ENTRY_H606C_velocity_actual_value &OD->list[46]
#define OD_ENTRY_H607A_target_position &OD->list[47]
#define OD_ENTRY_H607C_home_offset &OD->list[48]
#define OD_ENTRY_H607D_software_position_limit &OD->list[49]
#define OD_ENTRY_H607F_max_profile_velocity &OD->list[50]
#define OD_ENTRY_H6081_profile_velocity &OD->list[51]
#define OD_ENTRY_H6083_profile_acceleration &OD->list[52]
#define OD_ENTRY_H6084_profile_deceleration &OD->list[53]
#define OD_ENTRY_H6086_motion_profile_type &OD->list[54]
#define OD_ENTRY_H6098_homing_method &OD->list[55]
#define OD_ENTRY_H6099_homing_speeds &OD->list[56]
#define OD_ENTRY_H609A_homing_acceleration &OD->list[57]
#define OD_ENTRY_H60C0_interpolation_sub_mode_select &OD->list[58]
#define OD_ENTRY_H60C1_interpolation_data_record &OD->list[59]
#define OD_ENTRY_H60C2_interpolation_time_period &OD->list[60]
#define OD_ENTRY_H60C4_interpolation_data_configuration &OD->list[61]
#define OD_ENTRY_H60F4_following_error_actual_value &OD->list[62]
#define OD_ENTRY_H60FD_digital_inputs &OD->list[63]
#define OD_ENTRY_H60FF_target_velocity &OD->list[64]
#define OD_ENTRY_H6402_motor_type &OD->list[65]
#define OD_ENTRY_H6502_supported_drive_modes &OD->list[66]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
